### ISSUE TITLE
Failure to compile with GHC 9.10

### ISSUE THREAD

**Issue by ivanperez-keera** [GaloisInc/what4#272]
I'm finding an error when I try to compile `what4-1.6.1` with GHC 9.10.1:

```
src/What4/Utils/Word16String.hs:23:3: error: [GHC-87543]
    Ambiguous occurrence foldl'.
    It could refer to
       either Prelude.foldl',
              imported from `Prelude' at src/What4/Utils/Word16String.hs:30:1-57
              (and originally defined in `ghc-internal-9.1001.0:GHC.Internal.Data.Foldable'),
           or What4.Utils.Word16String.foldl',
              defined at src/What4/Utils/Word16String.hs:144:1.
   |
23 | , foldl'
   |   ^^^^^^
```

**Comment by RyanGlScott** [comment]
I've uploaded [`what4-1.6.2`](https://hackage.haskell.org/package/what4-1.6.2) to Hackage with a fix.
